---
  - name: Add resilio-sync repo key if OS Ubuntu
    apt_key:
      url: '{{ resilio_sync_apt_repo_key }}'
      state: present
    when: ansible_distribution == "Ubuntu"
    tags:
     - resilio-sync

  - name: Add resilio-sync repo address if OS Ubuntu
    apt_repository:
       repo: 'deb {{ resilio_sync_apt_repo_address }}'
       state: present
       filename: resilio-sync
    when: ansible_distribution == "Ubuntu"
    register: resil
    tags:
     - resilio-sync

  - name: Update package list if OS Ubuntu
    apt:
      update_cache: yes
    when: resil.changed and ansible_distribution == "Ubuntu"
    tags:
     - resilio-sync

  - name: Install package resilio-sync
    package:
      name: resilio-sync
      state: present
    tags:
     - resilio-sync

  - name: Import config file /etc/resilio-sync/config.json
    template:
      src: config.json.j2
      dest: /etc/resilio-sync/config.json
      owner: root
      group: root
      mode: 0644
    notify:
     - restart resilio-sync
    tags:
     - resilio-sync

  - name: Enable resilio-sync service
    systemd:
      name: resilio-sync
      state: started
      enabled: yes
